/*---------------------------------------------------------------------------*\
  Phase Density References (root) for beamWeldFoam

  Original authors:
      Thomas F. Flint, University of Manchester
      Gowthaman Parivendhan, University College Dublin
      Alojz Ivankovic, University College Dublin
      Michael C. Smith, University of Manchester
      Philip Cardiff, University College Dublin

  OpenFOAM 2412 port by:
      Pranay K. Pandey, Indian Institute of Space Science & Technology, Trivandrum
      github.com/Pranay1004

\*---------------------------------------------------------------------------*/

{
    const dimensionedScalar& rho1f(rho1);
    const dimensionedScalar& rho2f(rho2);
}
